name: sabang_es
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.2
  path: ^1.8.3
  qr_flutter: ^4.0.0
  mobile_scanner: ^7.0.1
  mailer: ^6.4.1
  file_picker: ^10.2.0
  csv: ^5.0.0
  uuid: ^3.0.7
  sqflite_common_ffi: ^2.3.6
  cupertino_icons: ^1.0.8
  pdf: ^3.10.4
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.2
  encrypt: ^5.0.3
  flutter_launcher_icons: ^0.14.4
  excel: ^4.0.6
  process_run: ^0.12.3+2
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  image_path: "assets/image/sabanges_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/image/sabanges_logo.png
    - assets/audio/success.mp3
    - assets/audio/failed.mp3

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
