name: Build & Upload APK Pre-release

on:
  push:
    tags:
      - 'v*'  # triggers on tags starting with "v", e.g. v1.0.0-beta

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.x'

      - name: Install dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release

      - name: Create or update GitHub pre-release
        run: |
          gh release create "${GITHUB_REF#refs/tags/}" \
            build/app/outputs/flutter-apk/app-release.apk \
            --prerelease \
            --title "Release ${GITHUB_REF#refs/tags/}" \
            --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
